### ISSUE TITLE
How to use it with Sycamore ?

### ISSUE THREAD

**Issue by danielnehrig** [notedge/panduck#4]
Can we get some example setups with sycamore
i looked at the project test cases and tried to implement it that way but unfortunatly
i run into errors when using the lib because notedown_ast uses onig and onig seems to not work with wasm target

**Comment by oovm** [comment]
Ok, I haven't updated `notedown ast` in a long time, I will republish the upstream https://github.com/notedge/notedown-rs

**Comment by oovm** [comment]
According to the description in https://github.com/rust-onig/rust-onig/blob/main/CHANGELOG.md#610, `onig` supports wasm.

And I have fixed `sycamore 0.8.1` api in `dev`.

**Comment by oovm** [comment]
In fact, the dependencies on the wasm side are very confusing, some directly use js libraries, some rely on rust re-implementation, and some have a tiny js engine embedded and compiled using rust to run in wasm (sounds crazy).
